### ISSUE TITLE
Enhance the script to allow it being used as a module

### ISSUE THREAD

**Issue by jessnoo** [Esri/511-Script#10]
Feedback from Transportation team

For organizations that want to incorporate the script into larger processes,  engineer the script to work as a module in other scripts in addition to working stand alone.

Known things that would need to be modified are:
- remove the main method
- make sub-functions private

**Comment by jessnoo** [comment]
@Erodenberg

**Comment by jessnoo** [comment]
Need to test this with multiple calls to the module in another script and vary things like whether a fgdb is defined, etc

**Comment by chris-fox** [comment]
You can now import SyncFeatureCollection as a module into another script and call the run() method to execute the sync. The run method also optionally takes a path to a config file:

import SyncFeatureCollection
SyncFeatureCollection.run(r"C:\Temp\SyncFeatureCollection.cfg")

**Comment by jessnoo** [comment]
Verified with #12 

Ran several tests including one script that contained the following four configurations via the module calls: full update, feature service only update, feature collection only update, full update. No issues observed when switching between different combinations of updates.
