### ISSUE TITLE
Make configuration file a script parameter

### ISSUE THREAD

**Issue by jessnoo** [Esri/511-Script#11]
Feedback from @erodenberg and Transportation team

Customers may have many GDBs that need to be synced and it's not intuitive how the script can be used for multiple GDBs. If we parameterize the config file, it will be easier for customers to manage more than one FGDB or Feature Collection updates

**Comment by chris-fox** [comment]
The script now takes one argument for the path to the config file, if no arguements are passed it will use the same logic to look for a file call SyncFeatureCollection.cfg in the same directory as the script. From command line:

python C:\Temp\SyncFeatureCollection.py C:\Temp\Configs\TestConfig1.cfg

**Comment by jessnoo** [comment]
Validated with #12
