### ISSUE TITLE
Check item type on input item ids

### ISSUE THREAD

**Issue by jessnoo** [Esri/511-Script#2]
add a check in the script to verify the type matches what's expected for the Feature Service and Feature Collection item ids passed into the script and report a friendly message to the user if the item type isn't what was expected.

**Comment by chris-fox** [comment]
We now check the item type associated with the feature service and feature collection item ids. If the item is not the correct type and error is thrown with a friendly error message and the script stops execution.

**Comment by jessnoo** [comment]
Verified with #12
