### ISSUE TITLE
Evaluate new overwrite feature collection capability

### ISSUE THREAD

**Issue by jessnoo** [Esri/511-Script#5]
With the Feb 29 AGOL update, the ability to directly overwrite a feature collection on export was added.  this was added as a requirement from the Transportation.  we need to evaluate this capability and implement as appropriate.

**Comment by chris-fox** [comment]
In the latest version of the script we are now just overwriting the feature collection (no longer doing the export to temp and updating the original).

**Comment by jessnoo** [comment]
Validated with #12 Feature Collection exports are happening successfully. Will submit new issues if something pops up during longer running tests.
