### ISSUE TITLE
Make FGDB upload and service overwrite optional

### ISSUE THREAD

**Issue by jessnoo** [Esri/511-Script#7]
Input from Transportation Team

Some organizations will have existing processes in place to update a hosted feature layer. In these cases, the file geodatabase upload and overwrite of the feature service are not needed. 

enhance the script to make the file geodatabase upload and feature service overwrite sections optional.

**Comment by jessnoo** [comment]
@Erodenberg

**Comment by chris-fox** [comment]
In the latest version if you don't provide a FGDB it will not upload the GDB or do the feature service update.

**Comment by jessnoo** [comment]
Validated with #12
