### ISSUE TITLE
Enhance error logging

### ISSUE THREAD

**Issue by jessnoo** [Esri/511-Script#9]
To better support troubleshooting of errors encountered during the execution of the script:
- capture more detailed error information
- capture job ids
- if possible, capture web request associated with failure

**Comment by chris-fox** [comment]
The script now logs the job id as well as the full response in any failed requests. I am not logging the full request yet as this may be a lot of text but we can discuss if we want to add this feature.

**Comment by jessnoo** [comment]
@chris-fox Setting up a long running test to try and get some errors.

@NikkiGolding FYI

**Comment by jessnoo** [comment]
Verified with #12 Job IDs are logged when failures happen with Online processes.
